apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodeapp
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp
  targetCPUUtilizationPercentage: 40