# Node APP
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: nodeapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: nodeapp:1.0
        name: nodeapp
        ports:
        - containerPort: 3000
        resources:
            requests:
              cpu: 500m (0.5)  1 sing colere
              memory: 256Mi 
            limits:
              cpu: 1000m
              memory: 512Mi
          
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
