apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    env: prod
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
  restartPolicy: Always
  hostname: nginx